### ISSUE TITLE
Need to make sure clutter is masked going into the attenuation correction code

### ISSUE THREAD

**Issue by scollis** [EVS-ATMOS/cmac2.0#64]
The output corrected Z filed contains clutter.. code does not yet accept gatefilter.. Need to decide if we fix in Py-ART first of just cludge cmac2.0

**Comment by scollis** [comment]
@rcjackson Can you look at the zphi code and see if we can set masked values in Z using a gatefilter as input.

**Comment by rcjackson** [comment]
It looks like it just masks the output wherever the input Z is masked. There is no support for a gatefilter.

**Comment by rcjackson** [comment]
Proper masking is now addressed by #66 and https://github.com/ARM-DOE/pyart/pull/817
